schema_version: 1

project:
  name: "stellar-attractor-site"
  slug: "stellar-attractor-site"
  description: "Stellar Attractor public website."
  type: "site"
  version: 0.1.0
  status: active

organization:
  name: IncusLuminis

repository:
  visibility: "public"
  default_branch: main
  template: true

license:
  id: MIT

storage:
  code: github
  content: github
  media: external